* Setup
** Python
Make sure python3 is installed on the system.
** virtual environment
You need to create a venv to hold the required packages
#+begin_src sh
  python3 -m venv .venv
#+end_src
Then activate the venv with:
#+begin_src sh
  # for Linux
  . .venv/bin/activate
  # for Windows
  .venv/Scripts/activate
#+end_src

Once you have created a venv use the following command to install the required packages from the requirements.txt.
 #+begin_src sh
  pip3 install -r requirements.txt
#+end_src
This should install the required libraries in to your virtual environment
** Initialize database
If everything has worked up untill now you are good to begin initialize the site. To create the database run the following command.
#+begin_src sh
  flask init-db
#+end_src
You should see the following message
#+begin_example
"Initialized the database."
#+end_example

** Load data
Even tho the database exists it is empty to populate it with the data run the load_data.py script found in the scripts/
The command is:
#+begin_src sh
  python3 scripts/load_data.py
#+end_src

** Launch App
from here run the app with the following command
#+begin_src sh
  flask run
#+end_src
This should launch the app and give you the local site address in the terminal.

* TODO Features
- [X] Finish the load_data.py script
- [ ] Rewrite the queries to pull info from all the tables
  - swap things like region id in the current view with the region id.
- [ ] Make the queries inject-able for the demo.
  - Currently They are using placeholders for queries.
