(use ./htmlElements/card)
(use ./structs/pokemon)
(use ./structs/gym)


(defn pokemon-list []
  (let  [bulbasaur (create-pokemon "1" "Bulbasaur" "Kanto" ["grass" "poison"] "images/Gen1/Bulbasaur.png")
        ivysaur (create-pokemon "2" "Ivysaur" "Kanto" ["grass" "poison"] "images/Gen1/Ivysaur.png")
        venusaur (create-pokemon "3" "Venusaur" "Kanto" ["grass" "poison"] "images/Gen1/Venusaur.png")
        charmander (create-pokemon "4" "Charmander" "Kanto" ["fire"] "images/Gen1/Charmander.png")
        charmeleon (create-pokemon "5" "Charmeleon" "Kanto" ["fire"] "images/Gen1/Charmeleon.png")
        charizard (create-pokemon "6" "Charizard" "Kanto" ["fire" "flying"] "images/Gen1/Charizard.png")
        squirtle (create-pokemon "7" "Squirtle" "Kanto" ["water"] "images/Gen1/Squirtle.png")
        wartortle (create-pokemon "8" "Wartortle" "Kanto" ["water"] "images/Gen1/Wartortle.png")
        blastoise (create-pokemon "9" "Blastoise" "Kanto" ["water"] "images/Gen1/Blastoise.png")
        caterpie (create-pokemon "10" "Caterpie" "Kanto" ["bug"] "images/Gen1/Caterpie.png")
        metapod (create-pokemon "11" "Metapod" "Kanto" ["bug"] "images/Gen1/Metapod.png")
        butterfree (create-pokemon "12" "Butterfree" "Kanto" ["bug" "flying"] "images/Gen1/Butterfree.png")
        weedle (create-pokemon "13" "Weedle" "Kanto" ["bug" "poison"] "images/Gen1/Weedle.png")
        kakuna (create-pokemon "14" "Kakuna" "Kanto" ["bug" "poison"] "images/Gen1/Kakuna.png")
        beedrill (create-pokemon "15" "Beedrill" "Kanto" ["bug" "poison"] "images/Gen1/Beedrill.png")
        pidgey (create-pokemon "16" "Pidgey" "Kanto" ["normal" "flying"] "images/Gen1/Pidgey.png")
        pidgeotto (create-pokemon "17" "Pidgeotto" "Kanto" ["normal" "flying"] "images/Gen1/Pidgeotto.png")
        pidgeot (create-pokemon "18" "Pidgeot" "Kanto" ["normal" "flying"] "images/Gen1/Pidgeot.png")
        rattata (create-pokemon "19" "Rattata" "Kanto" ["normal"] "images/Gen1/Rattata.png")
        raticate (create-pokemon "20" "Raticate" "Kanto" ["normal"] "images/Gen1/Raticate.png")
        spearow (create-pokemon "21" "Spearow" "Kanto" ["normal" "flying"] "images/Gen1/Spearow.png")
        fearow (create-pokemon "22" "Fearow" "Kanto" ["normal" "flying"] "images/Gen1/Fearow.png")
        ekans (create-pokemon "23" "Ekans" "Kanto" ["poison"] "images/Gen1/Ekans.png")
        arbok (create-pokemon "24" "Arbok" "Kanto" ["poison"] "images/Gen1/Arbok.png")
        pikachu (create-pokemon "25" "Pikachu" "Kanto" ["electric"] "images/Gen1/Pikachu.png")
        raichu (create-pokemon "26" "Raichu" "Kanto" ["electric"] "images/Gen1/Raichu.png")
        sandshrew (create-pokemon "27" "Sandshrew" "Kanto" ["ground"] "images/Gen1/Sandshrew.png")
        sandslash (create-pokemon "28" "Sandslash" "Kanto" ["ground"] "images/Gen1/Sandslash.png")
        nidoran-f (create-pokemon "29" "Nidoran♀" "Kanto" ["poison"] "images/Gen1/NidoranF.png")
        nidorina (create-pokemon "30" "Nidorina" "Kanto" ["poison"] "images/Gen1/Nidorina.png")
        nidoqueen (create-pokemon "31" "Nidoqueen" "Kanto" ["poison" "ground"] "images/Gen1/Nidoqueen.png")
        nidoran-m (create-pokemon "32" "Nidoran♂" "Kanto" ["poison"] "images/Gen1/NidoranM.png")
        nidorino (create-pokemon "33" "Nidorino" "Kanto" ["poison"] "images/Gen1/Nidorino.png")
        nidoking (create-pokemon "34" "Nidoking" "Kanto" ["poison" "ground"] "images/Gen1/Nidoking.png")
        clefairy (create-pokemon "35" "Clefairy" "Kanto" ["fairy"] "images/Gen1/Clefairy.png")
        clefable (create-pokemon "36" "Clefable" "Kanto" ["fairy"] "images/Gen1/Clefable.png")
        vulpix (create-pokemon "37" "Vulpix" "Kanto" ["fire"] "images/Gen1/Vulpix.png")
        ninetales (create-pokemon "38" "Ninetales" "Kanto" ["fire"] "images/Gen1/Ninetales.png")
        jigglypuff (create-pokemon "39" "Jigglypuff" "Kanto" ["normal" "fairy"] "images/Gen1/Jigglypuff.png")
        wigglytuff (create-pokemon "40" "Wigglytuff" "Kanto" ["normal" "fairy"] "images/Gen1/Wigglytuff.png")
        zubat (create-pokemon "41" "Zubat" "Kanto" ["poison" "flying"] "images/Gen1/Zubat.png")
        golbat (create-pokemon "42" "Golbat" "Kanto" ["poison" "flying"] "images/Gen1/Golbat.png")
        oddish (create-pokemon "43" "Oddish" "Kanto" ["grass" "poison"] "images/Gen1/Oddish.png")
        gloom (create-pokemon "44" "Gloom" "Kanto" ["grass" "poison"] "images/Gen1/Gloom.png")
        vileplume (create-pokemon "45" "Vileplume" "Kanto" ["grass" "poison"] "images/Gen1/Vileplume.png")
        paras (create-pokemon "46" "Paras" "Kanto" ["bug" "grass"] "images/Gen1/Paras.png")
        parasect (create-pokemon "47" "Parasect" "Kanto" ["bug" "grass"] "images/Gen1/Parasect.png")
        venonat (create-pokemon "48" "Venonat" "Kanto" ["bug" "poison"] "images/Gen1/Venonat.png")
        venomoth (create-pokemon "49" "Venomoth" "Kanto" ["bug" "poison"] "images/Gen1/Venomoth.png")
        diglett (create-pokemon "50" "Diglett" "Kanto" ["ground"] "images/Gen1/Diglett.png")
        dugtrio (create-pokemon "51" "Dugtrio" "Kanto" ["ground"] "images/Gen1/Dugtrio.png")
        meowth (create-pokemon "52" "Meowth" "Kanto" ["normal"] "images/Gen1/Meowth.png")
        persian (create-pokemon "53" "Persian" "Kanto" ["normal"] "images/Gen1/Persian.png")
        psyduck (create-pokemon "54" "Psyduck" "Kanto" ["water"] "images/Gen1/Psyduck.png")
        golduck (create-pokemon "55" "Golduck" "Kanto" ["water"] "images/Gen1/Golduck.png")
        mankey (create-pokemon "56" "Mankey" "Kanto" ["fighting"] "images/Gen1/Mankey.png")
        primeape (create-pokemon "57" "Primeape" "Kanto" ["fighting"] "images/Gen1/Primeape.png")
        growlithe (create-pokemon "58" "Growlithe" "Kanto" ["fire"] "images/Gen1/Growlithe.png")
	arcanine (create-pokemon "59" "Arcanine" "Kanto" ["fire"] "images/Gen1/Arcanine.png")
        poliwag (create-pokemon "60" "Poliwag" "Kanto" ["water"] "images/Gen1/Poliwag.png")
        poliwhirl (create-pokemon "61" "Poliwhirl" "Kanto" ["water"] "images/Gen1/Poliwhirl.png")
        poliwrath (create-pokemon "62" "Poliwrath" "Kanto" ["water" "fighting"] "images/Gen1/Poliwrath.png")
        abra (create-pokemon "63" "Abra" "Kanto" ["psychic"] "images/Gen1/Abra.png")
        kadabra (create-pokemon "64" "Kadabra" "Kanto" ["psychic"] "images/Gen1/Kadabra.png")
        alakazam (create-pokemon "65" "Alakazam" "Kanto" ["psychic"] "images/Gen1/Alakazam.png")
        machop (create-pokemon "66" "Machop" "Kanto" ["fighting"] "images/Gen1/Machop.png")
        machoke (create-pokemon "67" "Machoke" "Kanto" ["fighting"] "images/Gen1/Machoke.png")
        machamp (create-pokemon "68" "Machamp" "Kanto" ["fighting"] "images/Gen1/Machamp.png")
        bellsprout (create-pokemon "69" "Bellsprout" "Kanto" ["grass" "poison"] "images/Gen1/Bellsprout.png")
        weepinbell (create-pokemon "70" "Weepinbell" "Kanto" ["grass" "poison"] "images/Gen1/Weepinbell.png")
        victreebel (create-pokemon "71" "Victreebel" "Kanto" ["grass" "poison"] "images/Gen1/Victreebel.png")
        tentacool (create-pokemon "72" "Tentacool" "Kanto" ["water" "poison"] "images/Gen1/Tentacool.png")
        tentacruel (create-pokemon "73" "Tentacruel" "Kanto" ["water" "poison"] "images/Gen1/Tentacruel.png")
        geodude (create-pokemon "74" "Geodude" "Kanto" ["rock" "ground"] "images/Gen1/Geodude.png")
        graveler (create-pokemon "75" "Graveler" "Kanto" ["rock" "ground"] "images/Gen1/Graveler.png")
        golem (create-pokemon "76" "Golem" "Kanto" ["rock" "ground"] "images/Gen1/Golem.png")
        ponyta (create-pokemon "77" "Ponyta" "Kanto" ["fire"] "images/Gen1/Ponyta.png")
        rapidash (create-pokemon "78" "Rapidash" "Kanto" ["fire"] "images/Gen1/Rapidash.png")
        slowpoke (create-pokemon "79" "Slowpoke" "Kanto" ["water" "psychic"] "images/Gen1/Slowpoke.png")
        slowbro (create-pokemon "80" "Slowbro" "Kanto" ["water" "psychic"] "images/Gen1/Slowbro.png")
        magnemite (create-pokemon "81" "Magnemite" "Kanto" ["electric" "steel"] "images/Gen1/Magnemite.png")
        magneton (create-pokemon "82" "Magneton" "Kanto" ["electric" "steel"] "images/Gen1/Magneton.png")
        farfetchd (create-pokemon "83" "Farfetch'd" "Kanto" ["normal" "flying"] "images/Gen1/Farfetchd.png")
        doduo (create-pokemon "84" "Doduo" "Kanto" ["normal" "flying"] "images/Gen1/Doduo.png")
        dodrio (create-pokemon "85" "Dodrio" "Kanto" ["normal" "flying"] "images/Gen1/Dodrio.png")
        seel (create-pokemon "86" "Seel" "Kanto" ["water"] "images/Gen1/Seel.png")
        dewgong (create-pokemon "87" "Dewgong" "Kanto" ["water" "ice"] "images/Gen1/Dewgong.png")
        grimer (create-pokemon "88" "Grimer" "Kanto" ["poison"] "images/Gen1/Grimer.png")
        muk (create-pokemon "89" "Muk" "Kanto" ["poison"] "images/Gen1/Muk.png")
        shellder (create-pokemon "90" "Shellder" "Kanto" ["water"] "images/Gen1/Shellder.png")
        cloyster (create-pokemon "91" "Cloyster" "Kanto" ["water" "ice"] "images/Gen1/Cloyster.png")
        gastly (create-pokemon "92" "Gastly" "Kanto" ["ghost" "poison"] "images/Gen1/Gastly.png")
        haunter (create-pokemon "93" "Haunter" "Kanto" ["ghost" "poison"] "images/Gen1/Haunter.png")
        gengar (create-pokemon "94" "Gengar" "Kanto" ["ghost" "poison"] "images/Gen1/Gengar.png")
        onix (create-pokemon "95" "Onix" "Kanto" ["rock" "ground"] "images/Gen1/Onix.png")
        drowzee (create-pokemon "96" "Drowzee" "Kanto" ["psychic"] "images/Gen1/Drowzee.png")
        hypno (create-pokemon "97" "Hypno" "Kanto" ["psychic"] "images/Gen1/Hypno.png")
        krabby (create-pokemon "98" "Krabby" "Kanto" ["water"] "images/Gen1/Krabby.png")
        kingler (create-pokemon "99" "Kingler" "Kanto" ["water"] "images/Gen1/Kingler.png")
        voltorb (create-pokemon "100" "Voltorb" "Kanto" ["electric"] "images/Gen1/Voltorb.png")
        electrode (create-pokemon "101" "Electrode" "Kanto" ["electric"] "images/Gen1/Electrode.png")
        exeggcute (create-pokemon "102" "Exeggcute" "Kanto" ["grass" "psychic"] "images/Gen1/Exeggcute.png")
        exeggutor (create-pokemon "103" "Exeggutor" "Kanto" ["grass" "psychic"] "images/Gen1/Exeggutor.png")
        cubone (create-pokemon "104" "Cubone" "Kanto" ["ground"] "images/Gen1/Cubone.png")
        marowak (create-pokemon "105" "Marowak" "Kanto" ["ground"] "images/Gen1/Marowak.png")
        hitmonlee (create-pokemon "106" "Hitmonlee" "Kanto" ["fighting"] "images/Gen1/Hitmonlee.png")
        hitmonchan (create-pokemon "107" "Hitmonchan" "Kanto" ["fighting"] "images/Gen1/Hitmonchan.png")
        lickitung (create-pokemon "108" "Lickitung" "Kanto" ["normal"] "images/Gen1/Lickitung.png")
        koffing (create-pokemon "109" "Koffing" "Kanto" ["poison"] "images/Gen1/Koffing.png")
        weezing (create-pokemon "110" "Weezing" "Kanto" ["poison"] "images/Gen1/Weezing.png")
        rhyhorn (create-pokemon "111" "Rhyhorn" "Kanto" ["ground" "rock"] "images/Gen1/Rhyhorn.png")
        rhydon (create-pokemon "112" "Rhydon" "Kanto" ["ground" "rock"] "images/Gen1/Rhydon.png")
        chansey (create-pokemon "113" "Chansey" "Kanto" ["normal"] "images/Gen1/Chansey.png")
        tangela (create-pokemon "114" "Tangela" "Kanto" ["grass"] "images/Gen1/Tangela.png")
        kangaskhan (create-pokemon "115" "Kangaskhan" "Kanto" ["normal"] "images/Gen1/Kangaskhan.png")
        horsea (create-pokemon "116" "Horsea" "Kanto" ["water"] "images/Gen1/Horsea.png")
        seadra (create-pokemon "117" "Seadra" "Kanto" ["water"] "images/Gen1/Seadra.png")
        goldeen (create-pokemon "118" "Goldeen" "Kanto" ["water"] "images/Gen1/Goldeen.png")
        seaking (create-pokemon "119" "Seaking" "Kanto" ["water"] "images/Gen1/Seaking.png")
        staryu (create-pokemon "120" "Staryu" "Kanto" ["water"] "images/Gen1/Staryu.png")
        starmie (create-pokemon "121" "Starmie" "Kanto" ["water" "psychic"] "images/Gen1/Starmie.png")
        mr-mime (create-pokemon "122" "Mr. Mime" "Kanto" ["psychic" "fairy"] "images/Gen1/MrMime.png")
        scyther (create-pokemon "123" "Scyther" "Kanto" ["bug" "flying"] "images/Gen1/Scyther.png")
        jynx (create-pokemon "124" "Jynx" "Kanto" ["ice" "psychic"] "images/Gen1/Jynx.png")
        electabuzz (create-pokemon "125" "Electabuzz" "Kanto" ["electric"] "images/Gen1/Electabuzz.png")
        magmar (create-pokemon "126" "Magmar" "Kanto" ["fire"] "images/Gen1/Magmar.png")
        pinsir (create-pokemon "127" "Pinsir" "Kanto" ["bug"] "images/Gen1/Pinsir.png")
        tauros (create-pokemon "128" "Tauros" "Kanto" ["normal"] "images/Gen1/Tauros.png")
        magikarp (create-pokemon "129" "Magikarp" "Kanto" ["water"] "images/Gen1/Magikarp.png")
        gyarados (create-pokemon "130" "Gyarados" "Kanto" ["water" "flying"] "images/Gen1/Gyarados.png")
        lapras (create-pokemon "131" "Lapras" "Kanto" ["water" "ice"] "images/Gen1/Lapras.png")
        ditto (create-pokemon "132" "Ditto" "Kanto" ["normal"] "images/Gen1/Ditto.png")
        eevee (create-pokemon "133" "Eevee" "Kanto" ["normal"] "images/Gen1/Eevee.png")
        vaporeon (create-pokemon "134" "Vaporeon" "Kanto" ["water"] "images/Gen1/Vaporeon.png")
        jolteon (create-pokemon "135" "Jolteon" "Kanto" ["electric"] "images/Gen1/Jolteon.png")
        flareon (create-pokemon "136" "Flareon" "Kanto" ["fire"] "images/Gen1/Flareon.png")
        porygon (create-pokemon "137" "Porygon" "Kanto" ["normal"] "images/Gen1/Porygon.png")
        omanyte (create-pokemon "138" "Omanyte" "Kanto" ["rock" "water"] "images/Gen1/Omanyte.png")
        omastar (create-pokemon "139" "Omastar" "Kanto" ["rock" "water"] "images/Gen1/Omastar.png")
        kabuto (create-pokemon "140" "Kabuto" "Kanto" ["rock" "water"] "images/Gen1/Kabuto.png")
        kabutops (create-pokemon "141" "Kabutops" "Kanto" ["rock" "water"] "images/Gen1/Kabutops.png")
        aerodactyl (create-pokemon "142" "Aerodactyl" "Kanto" ["rock" "flying"] "images/Gen1/Aerodactyl.png")
        snorlax (create-pokemon "143" "Snorlax" "Kanto" ["normal"] "images/Gen1/Snorlax.png")
        articuno (create-pokemon "144" "Articuno" "Kanto" ["ice" "flying"] "images/Gen1/Articuno.png")
        zapdos (create-pokemon "145" "Zapdos" "Kanto" ["electric" "flying"] "images/Gen1/Zapdos.png")
        moltres (create-pokemon "146" "Moltres" "Kanto" ["fire" "flying"] "images/Gen1/Moltres.png")
        dratini (create-pokemon "147" "Dratini" "Kanto" ["dragon"] "images/Gen1/Dratini.png")
        dragonair (create-pokemon "148" "Dragonair" "Kanto" ["dragon"] "images/Gen1/Dragonair.png")
        dragonite (create-pokemon "149" "Dragonite" "Kanto" ["dragon" "flying"] "images/Gen1/Dragonite.png")
        mewtwo (create-pokemon "150" "Mewtwo" "Kanto" ["psychic"] "images/Gen1/Mewtwo.png")
        mew (create-pokemon "151" "Mew" "Kanto" ["psychic"] "images/Gen1/Mew.png")
	]
    (def pokelist 
      [bulbasaur ivysaur venusaur charmander charmeleon charizard squirtle wartortle blastoise
       caterpie metapod butterfree weedle kakuna beedrill pidgey pidgeotto pidgeot rattata
       raticate spearow fearow ekans arbok pikachu raichu sandshrew sandslash nidoran-f nidorina
       nidoqueen nidoran-m nidorino nidoking clefairy clefable vulpix ninetales jigglypuff wigglytuff
       zubat golbat oddish gloom vileplume paras parasect venonat venomoth diglett dugtrio meowth
       persian psyduck golduck mankey primeape growlithe arcanine poliwag poliwhirl poliwrath abra
       kadabra alakazam machop machoke machamp bellsprout weepinbell victreebel tentacool tentacruel
       geodude graveler golem ponyta rapidash slowpoke slowbro magnemite magneton farfetchd doduo dodrio
       seel dewgong grimer muk shellder cloyster gastly haunter gengar onix drowzee hypno krabby
       kingler voltorb electrode exeggcute exeggutor cubone marowak hitmonlee hitmonchan lickitung koffing
       weezing rhyhorn rhydon chansey tangela kangaskhan horsea seadra goldeen seaking staryu starmie
       mr-mime scyther jynx electabuzz magmar pinsir tauros magikarp gyarados lapras ditto eevee vaporeon
       jolteon flareon porygon omanyte omastar kabuto kabutops aerodactyl snorlax articuno zapdos
       moltres dratini dragonair dragonite mewtwo mew])))

(defn kanto-gym-list []
  (let [gym1 (create-gym "Pewter Gym" "Kanto" ["Brock"] "Boulder" "images/Gyms/Kanto/gym1.png")
	gym2 (create-gym "Cerulean Gym" "Kanto" ["Misty"] "Cascade" "images/Gyms/Kanto/gym2.png")
	gym3 (create-gym "Vermilion Gym" "Kanto" ["Lt. Surge"] "Thunder" "images/Gyms/Kanto/gym3.png")
	gym4 (create-gym "Celadon Gym" "Kanto" ["Erika"] "Rainbow" "images/Gyms/Kanto/gym4.png")
	gym5 (create-gym "Fuchsia Gym" "Kanto" ["Koga"] "Soul" "images/Gyms/Kanto/gym5.png")
	gym6 (create-gym "Saffron Gym" "Kanto" ["Sabrina"] "Marsh" "images/Gyms/Kanto/gym6.png")
	gym7 (create-gym "Cinnabar Gym" "Kanto" ["Blaine"] "Volcano" "images/Gyms/Kanto/gym7.png")
	gym8 (create-gym "Viridian Gym" "Kanto" ["Giovanni"] "Earth" "images/Gyms/Kanto/gym8.png")]
  
    (def kanto-gyms [gym1 gym2 gym3 gym4 gym5 gym6 gym7 gym8])
    kanto-gyms))

(defn johto-gym-list []
  (let [
    gym1 (create-gym "Violet Gym" "Johto" ["Falconer"] "Zephyr" "images/Gyms/Johto/gym1.png")
    gym2 (create-gym "Azalea Gym" "Johto" ["Bugsy"] "Hive" "images/Gyms/Johto/gym2.png")
    gym3 (create-gym "Goldenrod Gym" "Johto" ["Whitney"] "Plain" "images/Gyms/Johto/gym3.png")
    gym4 (create-gym "Ecruteak Gym" "Johto" ["Morty"] "Fog" "images/Gyms/Johto/gym4.png")
    gym5 (create-gym "Mahogany Gym" "Johto" ["Pryce"] "Ice" "images/Gyms/Johto/gym5.png")
    gym6 (create-gym "Blackthorn Gym" "Johto" ["Clair"] "Rising" "images/Gyms/Johto/gym6.png")
    gym7 (create-gym "Cianwood Gym" "Johto" ["Chuck"] "Storm" "images/Gyms/Johto/gym7.png")
    gym8 (create-gym "Olive Gym" "Johto" ["Jasmine"] "Mineral" "images/Gyms/Johto/gym8.png")]
  
    (def johto-gyms [gym1 gym2 gym3 gym4 gym5 gym6 gym7 gym8])
    johto-gyms))

(defn hoenn-gym-list []
  (let [
    gym1 (create-gym "Rustboro Gym" "Hoenn" ["Roxanne"] "Stone" "images/Gyms/Hoenn/gym1.png")
    gym2 (create-gym "Dewford Gym" "Hoenn" ["Brawly"] "Knuckle" "images/Gyms/Hoenn/gym2.png")
    gym3 (create-gym "Mauville Gym" "Hoenn" ["Wattson"] "Dynamo" "images/Gyms/Hoenn/gym3.png")
    gym4 (create-gym "Lavaridge Gym" "Hoenn" ["Flannery"] "Heat" "images/Gyms/Hoenn/gym4.png")
    gym5 (create-gym "Petalburg Gym" "Hoenn" ["Norman"] "Balance" "images/Gyms/Hoenn/gym5.png")
    gym6 (create-gym "Fortree Gym" "Hoenn" ["Winona"] " Feather" "images/Gyms/Hoenn/gym6.png")
    gym7 (create-gym "Mossdeep Gym" "Hoenn" ["Tate and Liza"] "Mind" "images/Gyms/Hoenn/gym7.png")
    gym8 (create-gym "Sootopolis Gym" "Hoenn" ["Wallace"] "Rain" "images/Gyms/Hoenn/gym8.png")]
  
    (def hoenn-gyms [gym1 gym2 gym3 gym4 gym5 gym6 gym7 gym8])
    hoenn-gyms))

(defn sinnoh-gym-list []
  (let [
    gym1 (create-gym "Oreburgh Gym" "Sinnoh" ["Roark"] "Coal" "images/Gyms/Sinnoh/gym1.png")
    gym2 (create-gym "Eterna Gym" "Sinnoh" ["Gardenia"] "Forest" "images/Gyms/Sinnoh/gym2.png")
    gym3 (create-gym "Hearthome Gym" "Sinnoh" ["Fantina"] "Relic" "images/Gyms/Sinnoh/gym3.png")
    gym4 (create-gym "Veilstone Gym" "Sinnoh" ["Maylene"] "Cobble" "images/Gyms/Sinnoh/gym4.png")
    gym5 (create-gym "Pastoria Gym" "Sinnoh" ["Crasher Wake"] "Fen" "images/Gyms/Sinnoh/gym5.png")
    gym6 (create-gym "Celestic Gym" "Sinnoh" ["Cynthia"] "Mind" "images/Gyms/Sinnoh/gym6.png")
    gym7 (create-gym "Snowpoint Gym" "Sinnoh" ["Candice"] "Icicle" "images/Gyms/Sinnoh/gym7.png")
    gym8 (create-gym "Sunyshore Gym" "Sinnoh" ["Volkner"] "Beacon" "images/Gyms/Sinnoh/gym8.png")]
  
    (def sinnoh-gyms [gym1 gym2 gym3 gym4 gym5 gym6 gym7 gym8])
    sinnoh-gyms))


