#+title: Demo Code

* Into
Just as a disclaimer this is all sample code and just to get an idea of how we can use these tools to accomplish the Project. This Example is just a simple database with a simple front end. The entire thing is written in js and html. What this example does is it uses an ORM (object relational mapping) to create object that will represent the relations in the database. This means most of the work is creating the classes and defining the relations between them. An ORM can also be used to query the server and handles most of the protection against sql injection as far as I can tell. This was my first time trying to program in js so this code might not be the best.

** Tools used:
Below is a list of tools used in this project. It is a fairly short list but I would recommend looking through and reading the docs. That is how I put together this project they are quite helpful. This is another reason most of this code needs to be reevaluated as it is mostly built out from the examples and tutorials from these tools.
- [[https://sequelize.org/][Sequelize]]
- [[https://expressjs.com/][Express]]
- [[https://tailwindcss.com/][Tailwind]]
- [[https://flowbite.com/docs/components/dropdowns/][Flowbite]]

** Running the demo.
Clone the repo then open a terminal or vscode navigate to the project and then run the command

#+begin_src shell
node src/app.js
#+end_src

This should display a message in the terminal that the server is up on localhost:5000/ Open this domain in your browser of choice, all design and development was done in firefox.

** Check out the site. 
Now you should be able to access the site add users search users and delete users give it a try, and be sure to check out the code to see how it works.